### ISSUE TITLE
How to divided the train data into 5 fold?

### ISSUE THREAD

**Issue by drumzhang** [emadeldeen24/eval_ssl_ssc#1]
Hello, I have divided the data set of sleep edf according to the data preprocessing method of TS-TCC, and generated three files, train.pt/valid.pt/test.py. But I don't know how to divide train.pt into five folders.
I get error: FileNotFoundError: [Errno 2] No such file or directory: 'data\\sleep_edf\\fold_0\\train_0_100per.pt'
Could you give me some suggestions?

**Comment by emadeldeen24** [comment]
I added a [file to do that](https://github.com/emadeldeen24/eval_ssl_ssc/blob/main/split_k-fold_and_few_labels.py).

**Comment by drumzhang** [comment]
thanks！

> I added a [file to do that](https://github.com/emadeldeen24/eval_ssl_ssc/blob/main/split_k-fold_and_few_labels.py).

**Comment by zhukaijie98** [comment]
> 谢谢！
> 
> > 我添加了一个[文件来做到这一点](https://github.com/emadeldeen24/eval_ssl_ssc/blob/main/split_k-fold_and_few_labels.py)。

What txt files are merged for data preprocessing to generate npz files?

**Comment by holydick99** [comment]
> Hello, I have divided the data set of sleep edf according to the data preprocessing method of TS-TCC, and generated three files, train.pt/valid.pt/test.py. But I don't know how to divide train.pt into five folders. I get error: FileNotFoundError: [Errno 2] No such file or directory: 'data\sleep_edf\fold_0\train_0_100per.pt' Could you give me some suggestions?

Hi，in your issue you mentioned you use TS-TCC's dataset and auther mentioned method to generate few-labels dataset. So could you please tell the details? In TS-TCC Epliepsy-data are .csv file and there is a prepocessing.py can split dataset, I have question is before I generate few-label data is split origin data in val.pt and train.pt with 0.3testsize?
